'use strict';
// Development-only browser validation. No authentication to real services is involved.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {spawn} = require('node:child_process');
const {chromium} = require('playwright');

(async () => {
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-os-browser-'));
  const root = path.join(temp, 'AI_AGENT_OS_QA');
  fs.mkdirSync(root);
  const fixture = spawn('python3', ['-u', 'tests/browser_fixture.py', root]);
  fixture.stderr.on('data', value => process.stderr.write(value));
  let browser;
  try {
    const port = await new Promise((resolve, reject) => {
      let received = '';
      const timeout = setTimeout(() => reject(Error('Fixture startup timeout')), 15000);
      fixture.stdout.on('data', value => {
        received += value.toString();
        if(received.includes('\n')) {clearTimeout(timeout);resolve(JSON.parse(received.split('\n')[0]).port);}
      });
      fixture.once('error', reject);
      fixture.once('exit', code => {if(code)reject(Error('Fixture exited: '+code));});
    });
    const secret = fs.readFileSync(path.join(root, '.agent-os/dashboard.token'), 'utf8').trim();
    browser = await chromium.launch({headless:true});
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`http://127.0.0.1:${port}/#token=${secret}`);
    await page.locator('#app').waitFor({state:'visible'});
    assert.equal(new URL(page.url()).hash, '', 'Access fragment must be cleared');
    assert.equal(await page.locator('#model').inputValue(), 'gpt-5.6-luna');
    assert.deepEqual(await page.locator('#settings-form input, #settings-form textarea, #settings-form select').evaluateAll(nodes=>nodes.map(n=>n.id)),['model','reasoning','fast']);
    assert.equal(await page.locator('#goals .goal').count(),1);
    assert.equal(await page.locator('#historical-goals .historical-goal').count(),0);
    await page.locator('#goal-history-summary').click();
    await page.locator('#historical-goals .historical-goal').first().waitFor();
    assert.equal(await page.locator('#historical-goals .historical-goal').count(),20);
    await page.locator('#history-more').click();
    await page.waitForFunction(()=>document.querySelectorAll('#historical-goals .historical-goal').length===40);
    await page.locator('#historical-goals .historical-goal').first().locator('summary').click();
    await page.locator('#historical-goals').getByText('Acceptance: Archived evidence').waitFor();
    await page.locator('#goal-history-summary').click();
    const projectLink=page.locator('#projects a');
    assert.equal(await projectLink.getAttribute('href'), 'http://localhost:8800');
    assert.equal(await projectLink.getAttribute('target'), '_blank');
    assert.equal(await page.locator('#framework-apply').isDisabled(), true);
    const bootstrapHistory=page.locator('[data-goal-id="bootstrap"] details').filter({has:page.locator('summary',{hasText:'Diagnostic history'})});
    const strategyDetail=page.locator('[data-goal-id="bootstrap"] .strategy-detail');
    await strategyDetail.locator('summary').click();
    await strategyDetail.getByText('docs/provider-contract.md',{exact:false}).waitFor();
    await bootstrapHistory.locator('summary').click();
    await bootstrapHistory.locator('.diagnostic-history').filter({hasText:'Dashboard connectivity verified'}).waitFor();
    const refreshed=await page.locator('#last-refresh').textContent();
    await page.waitForFunction(value=>document.getElementById('last-refresh').textContent!==value,refreshed);
    assert.equal(await bootstrapHistory.evaluate(el=>el.open), true, 'Open history should survive polling');
    assert.equal(await strategyDetail.evaluate(el=>el.open), true, 'Open strategy should survive polling');
    await page.locator('#goal-title').fill('Weekly report');
    await page.locator('#goal-description').fill('Create a report with sample data and instructions in GitHub.');
    await page.locator('#goal-acceptance').fill('The file exists and its totals match the sample data.');
    await page.locator('#goal-form button[type=submit]').click();
    await page.locator('#goals h3').filter({hasText:'Weekly report'}).waitFor();
    const goalRow=page.locator('#goals .goal').filter({has:page.locator('h3',{hasText:'Weekly report'})});
    const goalId=await goalRow.getAttribute('data-goal-id');
    await page.locator('#guidance-goal').selectOption(goalId);
    await page.locator('#guidance-key').fill('verification-method');
    await page.locator('#guidance-body').fill('Wait for a service event and continue documentation.');
    // Polling must not discard an instruction being composed.
    const guidanceRefresh=await page.locator('#last-refresh').textContent();
    await page.waitForFunction(value=>document.getElementById('last-refresh').textContent!==value,guidanceRefresh);
    assert.equal(await page.locator('#guidance-body').inputValue(), 'Wait for a service event and continue documentation.');
    await page.locator('#guidance-form button[type=submit]').click();
    await goalRow.locator('.guidance-item').filter({hasText:'Wait for a service event'}).waitFor();
    await goalRow.getByRole('button',{name:'Edit guidance',exact:true}).click();
    await page.locator('#guidance-body').fill('Use the status file for verification.');
    await page.locator('#guidance-form button[type=submit]').click();
    await goalRow.locator('.guidance-item').filter({hasText:'(v2)'}).waitFor();
    await page.reload();
    await page.locator('#app').waitFor({state:'visible'});
    await goalRow.locator('.guidance-item').filter({hasText:'Use the status file'}).waitFor();
    await page.locator('#model').fill('gpt-6-astra');
    await page.locator('#reasoning').fill('high');
    await page.locator('#fast').check();
    await page.locator('#settings-form button[type=submit]').click();
    await page.waitForFunction(() => document.getElementById('notice').textContent.includes('Settings saved'));
    await page.reload();
    await page.locator('#app').waitFor({state:'visible'});
    assert.equal(await page.locator('#model').inputValue(), 'gpt-6-astra');
    assert.equal(await page.locator('#fast').isChecked(), true);
    await page.locator('#pause').click();
    await page.waitForFunction(() => document.getElementById('pause').textContent === 'Resume');
    assert.equal(await page.locator('#framework-apply').isDisabled(), false);
    await page.locator('#pause').click();
    await page.waitForFunction(() => document.getElementById('pause').textContent === 'Pause');
    fs.mkdirSync('browser-artifacts', {recursive:true});
    await page.screenshot({path:'browser-artifacts/dashboard-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Mobile layout must not overflow');
    await page.screenshot({path:'browser-artifacts/dashboard-mobile.png',fullPage:true});
    await goalRow.getByRole('button',{name:'Clear guidance',exact:true}).click();
    await goalRow.locator('.guidance-item').waitFor({state:'detached'});
    await page.getByRole('button',{name:'Cancel',exact:true}).click();
    await goalRow.waitFor({state:'detached'});
    await page.locator('#goal-history-summary').click();
    await page.locator('#historical-goals summary').filter({hasText:'Weekly report · Cancelled'}).waitFor();
    assert.equal(await page.locator('#goals').getByText('Weekly report',{exact:true}).count(),0);
    await page.locator('#goal-title').fill('<img src=x onerror=alert(1)>');
    await page.locator('#goal-description').fill('Render this as text.');
    await page.locator('#goal-acceptance').fill('No injected HTML nodes.');
    await page.locator('#goal-form button[type=submit]').click();
    await page.locator('#goals h3').filter({hasText:'<img src=x onerror=alert(1)>'}).waitFor();
    assert.equal(await page.locator('#goals img').count(), 0);
    assert.deepEqual(errors, []);
    fs.writeFileSync('browser-artifacts/result.json', JSON.stringify({passed:true,checks:['authentication fragment removal','goal submission','persistent guidance creation, replacement, reload and clearing','guidance input survives polling','model and Fast persistence','only Model Reasoning Fast settings','terminal history pagination and details','separate project link','history survives polling','update pause gate','pause and resume','cancellation','mobile overflow','HTML injection prevention','no page JavaScript errors']},null,2));
    console.log('Browser workflow passed: desktop, mobile, goals, settings, controls and text rendering.');
  } finally {
    if(browser)await browser.close();
    fixture.kill('SIGTERM');
    await new Promise(resolve => {if(fixture.exitCode !== null)resolve();else fixture.once('exit',resolve);});
    fs.rmSync(temp,{recursive:true,force:true});
  }
})().catch(error => {console.error(error);process.exitCode=1;});
